#!/usr/bin/fish

# Usage: findedit [FUZZY_MATCH] [ROOT_DIR]


if test -n "$argv[1]"
    set fzf_flags --query=$argv[1]
end

if test -n "$argv[2]"
    set root_dir $argv[2]
else
    set root_dir $HOME
end

set target (fd --hidden --type f . $root_dir | fzf $fzf_flags --preview='bat --color=always {}' --preview-window=up:80%)
test -n "$target" || exit 1

emacsclient --no-wait $target

# Switch to Awesome Window Manager tag 2 (emacs)
# awmtag 2
