#!/usr/bin/env python3
#
# Kubernetes context switcher.

import click
from subprocess import run

@click.command()
@click.argument('context')
@click.option('--namespace', default=None, help='Set default namespace in the new context.')
def use(context, namespace):
    cmd = f"kubectl config use-context {context}"
    run(cmd.split())
    if namespace:
        cmd = f"kubectl config set-context {context} --namespace={namespace}"
        run(cmd.split())

if __name__ == '__main__':
    use()

