#!/usr/bin/env fish

set project (
  gcloud projects list --format="value(project_id)" |
    sort --reverse |
    fzf --query "$argv[1]" --select-1 --prompt='project> '
)
test -n "$project" || exit 1

echo Switching project to $project...
gcloud config set project $project
